sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) 
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1  
before_install: 
   - sudo apt-get install -y libssl-dev libffi-dev python-dev build-essential
   - bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" --accept-all-defaults
   - oci --help
   - oci --version
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- -- coverage 

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
